development:
  adapter: mysql2
  database: movies_development
  username: root
  password:
  host: localhost

test:
  adapter: mysql2
  database: movies_test
  username: root
  password:
  host: localhost